# Site settings
title: My Struggle
description: Life goes on
baseurl: "" 
url: #"https://bemself.github.io"

# GitHub User settings
username: My Struggle
github_username: bemself
user_description: Life is struggling?
user_title: Nobody
email: doituself@outlook.com

# Blog Author settings
author:
  name:           My Struggle
  picture:        
  email:          doituself@outlook.com
  description:
  twitter:
  facebook:
  github:         https://github.com/bemself
  linkedin:
  clustrmap:      #fill in you clustrmap string. 


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  

permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: true
      status: Completed
      protected: false
      commentable: true
      rss: true
# Post wordcount display settings
post_wordcount:
  item_text: true
  wordcount: true
  min2read: true
  separated_meta: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"